# Generated by Django 5.2.4 on 2025-07-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensagem',
            new_name='Mensagens',
        ),
    ]
